apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-slave
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Updated to use 'standard'
  resources:
    requests:
      storage: 5Gi
