apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
data:
  REDIS_ADDR: "redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  POSTGRES_URL: "postgres://user:password@postgres:5432/ordersdb?sslmode=disable"
