version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    

  postgres2:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productsdb
    ports:
      - "5433:5432"  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  orders-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_URL=postgres://user:password@postgres:5432/ordersdb?sslmode=disable
      - POSTGRES2_URL=postgres://user:password@postgres2:5432/productsdb?sslmode=disable

    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started