apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image:  phatbb119/orders-service:latest
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: POSTGRES_URL
          value: "postgres://user:password@postgres:5432/ordersdb?sslmode=disable"
        - name: POSTGRES2_URL
          value: postgres://user:password@postgres2:5432/productsdb?sslmode=disable
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: orders-service-config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  type: NodePort  
  ports:
    - protocol: TCP
      port: 80               
      targetPort: 8000    
      nodePort: 30007        
