apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres2
  template:
    metadata:
      labels:
        app: postgres2
    spec:
      containers:
        - name: postgres2
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: productsdb
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-sql
          configMap:
            name: init-sql

---
apiVersion: v1
kind: Service
metadata:
  name: postgres2
spec:
  ports:
    - port: 5432
  selector:
    app: postgres2
