apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==        # Base64 encoded "user"
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # Base64 encoded "password"
  POSTGRES_DB: b3JkZXJzZGI=      # Base64 encoded "ordersdb"
